"use client";
import { useEffect, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { cinemaEase } from "@/animations/motion";
import { eventConfig } from "@/config/event";

const labels=["jours","heures","minutes","secondes"];
function getState(){const now=Date.now(),start=new Date(eventConfig.startDate).getTime(),end=new Date(eventConfig.endDate).getTime();if(now>=end)return{phase:"after" as const,time:null};if(now>=start)return{phase:"live" as const,time:null};const d=start-now;return{phase:"before" as const,time:{days:Math.floor(d/86400000),hours:Math.floor(d/3600000)%24,minutes:Math.floor(d/60000)%60,seconds:Math.floor(d/1000)%60}}}
export function AnnouncementCountdown(){const [state,setState]=useState<ReturnType<typeof getState>>();const reduced=useReducedMotion();useEffect(()=>{const update=()=>setState(getState());update();const timer=window.setInterval(update,1000);return()=>clearInterval(timer)},[]);const values=state?.time?[state.time.days,state.time.hours,state.time.minutes,state.time.seconds].map(v=>String(v).padStart(2,"0")):state?null:["XX","XX","XX","XX"];return <div className="announcement-countdown" aria-live="polite"><div><p className="eyebrow">Le rendez-vous approche.</p><h3>27 août 2026</h3><p className="countdown-note">Le 27 août 2026, les portes du château s'ouvriront à un cercle limité d'entrepreneurs venus créer des connexions qui comptent.</p></div>{values?<div className="countdown-values">{values.map((v,i)=><span key={labels[i]}><span className="countdown-window"><AnimatePresence mode="popLayout" initial={false}><motion.b key={v} initial={reduced?false:{opacity:0,y:"30%"}} animate={{opacity:1,y:0}} exit={reduced?undefined:{opacity:0,y:"-30%"}} transition={{duration:reduced ? .08 : .28,ease:cinemaEase}}>{v}</motion.b></AnimatePresence></span><small>{labels[i]}</small></span>)}</div>:<p className="countdown-revealed">{state?.phase==="live"?"L'expérience commence maintenant.":"La prochaine édition sera annoncée prochainement."}</p>}</div>}
