import Image from "next/image";
import { ArrowRight, Check, Mail, MessageCircle } from "lucide-react";
import { eventConfig as event } from "@/config/event";
import { Reveal } from "@/components/Reveal";
import { Button } from "@/components/Button";
import { Navigation } from "@/components/Navigation";
import { ApplicationForm } from "@/components/ApplicationForm";
import { Faq } from "@/components/Faq";
import { ArrivalHero } from "@/components/ArrivalHero";
import { BrandMark } from "@/components/BrandMark";
import { ExperienceEnvironment } from "@/components/ExperienceEnvironment";
import { AnnouncementCountdown } from "@/components/AnnouncementCountdown";
import { SpeakersSection } from "@/sections/SpeakersSection";
import { ProgramSection } from "@/sections/ProgramSection";
import { MotionHeading } from "@/components/motion/MotionHeading";
import { RevealImage } from "@/components/motion/RevealImage";
import { StaggerGroup, StaggerItem } from "@/components/motion/StaggerGroup";
import { SectionTransition } from "@/components/motion/SectionTransition";

export function LandingPage(){return <><ExperienceEnvironment/><Navigation/><main><ArrivalHero/>
  <section id="networking" className="cinematic-section networking-rebuilt"><div className="wrap"><Reveal variant="lateralLeft"><p className="eyebrow">Les rencontres</p><MotionHeading>{event.networking.title}</MotionHeading><p className="section-copy">{event.networking.primary}</p></Reveal><div className="network-composition"><RevealImage className="network-photo"><Image src={event.images.experience} alt="Entrepreneurs en conversation autour d'une table" fill sizes="(max-width: 760px) 100vw, 62vw"/></RevealImage><Reveal className="network-aside" variant="lateralRight"><p>{event.networking.secondary}</p><StaggerGroup className="network-editorial">{event.networking.outcomes.map((item,i)=><StaggerItem className="network-line" key={item}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{item}</h3><small>{i===0?"Collaborations · partenaires":i===1?"Clients · introductions":"Conseils · nouvelles perspectives"}</small></div><ArrowRight/></StaggerItem>)}</StaggerGroup><Button href="#candidature" variant="ghost" className="section-cta">Candidater</Button></Reveal></div></div><SectionTransition type="warm-gradient"/></section>
  <section id="identification" className="cinematic-section identification-scene"><div className="wrap"><Reveal variant="quiet"><p className="eyebrow">Ta place dans le cercle</p><MotionHeading>{event.identification.title}</MotionHeading><p className="section-copy">{event.identification.text}</p><blockquote>{event.identification.statement}</blockquote></Reveal><StaggerGroup className="identification-points">{event.identification.points.map((point,i)=><StaggerItem key={point}><span>0{i+1}</span><p>{point}</p></StaggerItem>)}</StaggerGroup></div><SectionTransition type="image-dissolve"/></section>
  <section id="conferences" className="cinematic-section conference-scene"><div className="wrap"><Reveal variant="lateralLeft"><p className="eyebrow">Les conférences</p><MotionHeading>{event.conferences.title}</MotionHeading><p className="section-copy">{event.conferences.text}</p></Reveal><RevealImage className="wide-frame"><Image src={event.images.workshop} alt="Prise de parole et échanges dans le château" fill sizes="100vw" className="cover"/><span>{event.conferences.statement}</span></RevealImage><StaggerGroup className="topic-flow">{event.conferences.topics.map(topic=><StaggerItem key={topic}><span>{topic}</span></StaggerItem>)}</StaggerGroup></div><SectionTransition type="light-sweep"/></section>
  <SpeakersSection/>
  <section className="cinematic-section announcement-scene"><div className="wrap"><Reveal variant="stately"><AnnouncementCountdown/></Reveal><Reveal variant="quiet"><Button href="#candidature" variant="ghost" className="section-cta">Candidater</Button></Reveal></div><SectionTransition type="dark-veil"/></section>
  <section id="domaine" className="domain domain-rebuilt"><div className="domain-image"><Image src={event.images.domain} alt="Château entièrement privatisé en Bretagne" fill sizes="100vw" className="cover"/><div className="domain-overlay"/><div className="wrap domain-copy"><Reveal variant="lateralLeft"><p className="eyebrow">Le domaine</p><MotionHeading>{event.domain.title}</MotionHeading><p>{event.domain.text}</p></Reveal></div></div><div className="wrap domain-mosaic"><RevealImage><figure><Image src={event.images.workshop} alt="Salle destinée aux échanges et conférences" fill sizes="(max-width: 760px) 88vw, 58vw"/></figure></RevealImage><RevealImage><figure><Image src={event.images.experience} alt="Repas et conversations dans le domaine" fill sizes="(max-width: 760px) 68vw, 32vw"/></figure></RevealImage></div><StaggerGroup className="wrap features">{event.domain.features.map((item,i)=><StaggerItem key={item}><span><b>{String(i+1).padStart(2,"0")}</b>{item}</span></StaggerItem>)}</StaggerGroup><SectionTransition type="warm-gradient"/></section>
  <section id="experience" className="cinematic-section immersion-rebuilt"><div className="wrap"><Reveal variant="quiet"><p className="eyebrow">L'expérience</p><MotionHeading>{event.experience.title}</MotionHeading><p className="section-copy">{event.experience.text}</p></Reveal><div className="experience-sequence" aria-label="Le parcours de l'expérience"><span>Arriver</span><span>Rencontrer</span><span>Apprendre</span><span>Échanger</span><span>Partager</span><span>Repartir autrement</span></div><StaggerGroup className="experience-triptych">{event.experiences.map((item,i)=><StaggerItem key={item.title}><span>0{i+1}</span><h3>{item.title}</h3><p>{item.text}</p></StaggerItem>)}</StaggerGroup></div><SectionTransition type="dark-veil"/></section>
  <ProgramSection/>
  <section id="rarete" className="cinematic-section scarcity-scene"><div className="wrap narrative-split"><Reveal variant="lateralLeft"><p className="eyebrow">Le format</p><MotionHeading>{event.scarcity.title}</MotionHeading><p className="section-copy">{event.scarcity.text}</p></Reveal><StaggerGroup className="scarcity-points">{event.scarcity.points.map((point,i)=><StaggerItem key={point}><span>0{i+1}</span><p>{point}</p></StaggerItem>)}</StaggerGroup></div><SectionTransition type="gold-line"/></section>
  <section id="billets" className="cinematic-section tickets tickets-rebuilt"><div className="wrap"><Reveal variant="quiet"><p className="eyebrow">Les accès</p><MotionHeading>Choisis la manière dont tu veux vivre Destination Bretagne.</MotionHeading><p className="section-copy">Trois formats, une même intention : créer les conditions de rencontres qui comptent.</p></Reveal><StaggerGroup className="ticket-grid">{event.tickets.map(ticket=><StaggerItem className={`ticket ${ticket.featured?"featured":""}`} key={ticket.name}>{ticket.badge&&<span className="ticket-badge">{ticket.badge}</span>}<p className="ticket-intent">{ticket.note}</p><h3>{ticket.name}</h3><strong className="price">{ticket.price}</strong><ul>{ticket.benefits.map(benefit=><li key={benefit}><Check/>{benefit}</li>)}</ul><Button href={ticket.href} variant={ticket.featured?"gold":"ghost"}>{ticket.cta}</Button><small className="ticket-safe">Aucun paiement à cette étape</small></StaggerItem>)}</StaggerGroup><div className="ticket-comparison" aria-label="Comparaison rapide des pass"><span>Découverte <b>1 journée</b></span><span>Expérience <b>3 jours · sans hébergement</b></span><span>Immersion <b>3 jours · hébergement inclus</b></span></div></div><SectionTransition type="soft-fade"/></section>
  <section id="organisateur" className="cinematic-section organizer-scene"><div className="wrap organizer-grid"><RevealImage className="organizer-photo"><div className="organizer-portrait" role="img" aria-label="Portrait éditorial temporaire d'Aron"><span>ARON</span><i>Fondateur de Destination Bretagne</i></div></RevealImage><Reveal variant="lateralRight"><p className="eyebrow">L'origine du projet</p><MotionHeading>Pourquoi Destination Bretagne existe.</MotionHeading><h3>{event.organizer.name}</h3><p className="organizer-meta">{event.organizer.role}</p>{event.organizer.text.map(text=><p key={text}>{text}</p>)}<p className="organizer-proof">Son activité SaaS atteint aujourd'hui {event.organizer.result}, un résultat communiqué par Aron.</p><a href={event.links.instagram}>{event.organizer.instagram}</a></Reveal></div><SectionTransition type="soft-fade"/></section>
  <section id="faq" className="cinematic-section faq faq-rebuilt"><div className="wrap faq-layout"><Reveal variant="lateralLeft"><p className="eyebrow">Avant de candidater</p><MotionHeading>Les réponses utiles.</MotionHeading><Button href={event.links.whatsapp} variant="ghost">Poser une question</Button></Reveal><Faq/></div><SectionTransition type="image-dissolve"/></section>
  <section id="candidature" className="reservation-rebuilt"><Image src={event.images.final} alt="Conversation entre entrepreneurs autour d'une table" fill sizes="100vw" loading="eager" className="cover"/><div className="reservation-shade"/><div className="wrap reservation-grid"><Reveal variant="lateralLeft"><p className="eyebrow">{event.final.eyebrow}</p><MotionHeading>{event.final.title}</MotionHeading><p>{event.final.text}</p><div className="final-facts">{event.final.facts.map(fact=><span key={fact}>{fact}</span>)}</div><div className="contact-lines"><a href={event.links.email}><Mail/>{event.contact.email}</a><a href={event.links.whatsapp}><MessageCircle/>{event.final.secondaryCta}</a></div></Reveal><Reveal variant="lateralRight"><ApplicationForm/></Reveal></div></section>
  </main><footer><div className="wrap footer-minimal"><div className="brand footer-brand"><BrandMark/></div><div><p>{event.dates}</p><p>{event.location}</p></div><div><a href={event.links.instagram}>Instagram</a><a href={event.links.email}>Email</a></div></div><div className="wrap copyright">© 2026 {event.name}. Tous droits réservés.</div></footer><a className="mobile-book" href="#candidature"><span><b>{event.final.primaryCta}</b><small>{event.dates}</small></span><ArrowRight/></a></>}
