export const eventConfig = {
  name: "Destination Bretagne",
  shortName: "DESTINATION BRETAGNE",
  eyebrow: "MASTERMIND ENTREPRENEURIAL · BRETAGNE",
  startDate: "2026-08-27T17:00:00+02:00",
  endDate: "2026-08-29T18:00:00+02:00",
  dateISO: { start: "2026-08-27T17:00:00+02:00", end: "2026-08-29T18:00:00+02:00" },
  timezone: "Europe/Paris",
  dates: "27 — 29 août 2026",
  location: "Château privatisé en Bretagne",
  address: "Bretagne, France",
  participantRange: "30 à 50",
  capacityLabel: "30 à 50",
  capacity: 50,
  beds: 10,
  remainingPlaces: "Sur demande",
  availabilityUpdated: "1 août 2026",
  bookingDeadline: "Date communiquée prochainement",
  mainPromise: "Deux jours pour transformer ton réseau.",
  promise: "Deux jours pour transformer ton réseau.",
  finalStatement: "Les opportunités appartiennent à ceux qui passent à l'action.",
  centralValue: "Chacun apporte de la valeur.",
  description: "Mastermind entrepreneurial premium et expérience de networking dans un château entièrement privatisé en Bretagne, du 27 au 29 août 2026.",
  siteUrl: "https://destination-bretagne.vercel.app",
  instagram: "@aron.etp",
  links: { booking:"#candidature", application:"#candidature", whatsapp:"https://wa.me/33600000000", instagram:"https://instagram.com/aron.etp", email:"mailto:bonjour@destination-bretagne.fr", legal:"", terms:"", privacy:"", externalForm:"" },
  contact: { email:"bonjour@destination-bretagne.fr", whatsapp:"+33 6 00 00 00 00", instagram:"@aron.etp" },
  images: { hero:"/images/hero-domain.webp", domain:"/images/domain-morning.webp", experience:"/images/dinner-conversation.webp", workshop:"/images/workshop-manor.webp", final:"/images/dinner-conversation.webp" },
  hero: {
    subtitle:"Du 27 au 29 août 2026, rejoins 30 à 50 entrepreneurs dans un château entièrement privatisé pour créer des relations qui continueront bien après l'événement.",
    facts:["27 — 29 août 2026","Château privatisé en Bretagne","30 à 50 participants","Networking, conférences et expérience immersive"],
    primaryCta:"Candidater", secondaryCta:"Découvrir l'expérience",
  },
  networking: {
    title:"Les bonnes rencontres accélèrent tout.",
    primary:"Une idée peut changer un projet. Une introduction peut ouvrir une porte. Une conversation peut devenir une collaboration. Destination Bretagne a été imaginé pour multiplier ces moments, loin des échanges rapides et superficiels des événements traditionnels.",
    secondary:"Pendant plusieurs jours, tu partageras le même lieu, les mêmes repas et les mêmes expériences que des entrepreneurs aux parcours différents, mais animés par la même volonté d'avancer.",
    outcomes:["Des relations durables","Des opportunités concrètes","Des regards qui font avancer"],
  },
  identification: {
    title:"Tu n'as pas besoin d'avoir tout accompli pour avoir ta place.",
    text:"Certains participants lanceront leur premier projet. D'autres développeront déjà une activité rentable. Cette diversité fait partie de la valeur de l'expérience : chacun arrive avec un parcours, une compétence et une vision à partager.",
    statement:"La seule condition : venir avec l'envie d'échanger et d'apporter de la valeur.",
    points:["Tu peux venir seul","Tu peux être débutant","Tu peux être déjà confirmé","Tu seras guidé dans les premiers échanges","L'événement est pensé pour faciliter les rencontres"],
  },
  conferences: { title:"Des expériences concrètes, partagées sans filtre.", text:"Les conférences sont conçues pour aller au-delà des discours génériques. Chaque intervenant partage les décisions, les méthodes et les apprentissages qui ont réellement marqué son parcours.", statement:"Les conférences créent les idées. Les échanges qui suivent leur donnent une direction.", topics:["Stratégie","Acquisition","Produit","Vision"] },
  domain: { title:"Un château privatisé pour sortir du cadre habituel.", text:"Pendant l'événement, le domaine devient un espace entièrement consacré aux échanges, aux idées et aux rencontres. Aucun public extérieur. Aucun passage permanent. Seulement les participants, les intervenants et l'équipe de Destination Bretagne.", features:["Domaine entièrement privatisé","Piscine","Espaces extérieurs","Salles de conférence","Espaces pour discuter","Repas","Hébergement selon les formules","Soirée house"] },
  domainFeatures:["Domaine privatisé","Piscine","Espaces extérieurs","Salles de conférence","Espaces d'échange","Repas","Hébergement","Soirée house"],
  experience: { title:"Ce sont souvent les moments imprévus que l'on retient.", text:"Une discussion après une conférence. Une idée partagée pendant le dîner. Une rencontre au bord de la piscine. Une conversation qui se prolonge bien après le programme. Destination Bretagne est conçu pour laisser de la place à ces moments." },
  experiences:[
    {icon:"Mic2",title:"Conférences",text:"Des décisions, des méthodes et des apprentissages issus du terrain."},
    {icon:"Users",title:"Échanges spontanés",text:"Des conversations rendues possibles par plusieurs jours passés au même endroit."},
    {icon:"Lightbulb",title:"Ateliers",text:"Des idées mises à l'épreuve de regards différents."},
  ],
  speakers:[
    {id:"01",expertise:"Projets digitaux",name:"Aron",role:"Entrepreneur, organisateur et SaaS Founder",result:"10 k€ par mois",status:"CONFIRMÉ",image:""},
    {id:"02",expertise:"Croissance et automatisation",name:"Ayden",role:"SaaS Founder",result:"15 k€ par mois",status:"CONFIRMÉ",image:""},
    {id:"03",expertise:"Marque et positionnement",name:"Félicien",role:"Créateur de SaaS",result:"30 k€ par mois",status:"CONFIRMÉ",image:""},
    {id:"04",expertise:"Intervenant mystère",name:"Prochaine annonce",role:"Profil en cours de sélection.",result:"",status:"EN SÉLECTION",image:""},
    {id:"05",expertise:"Intervenant mystère",name:"Prochaine annonce",role:"Profil en cours de sélection.",result:"",status:"EN SÉLECTION",image:""},
    {id:"06",expertise:"Intervenant mystère",name:"Prochaine annonce",role:"Profil en cours de sélection.",result:"",status:"EN SÉLECTION",image:""},
  ],
  schedule:[
    {day:"Jeudi 27 août 2026",date:"L'arrivée",items:["À partir de 17 h 00 — Accueil des participants","Découverte du château","Installation","Premiers échanges","Piscine","Moment de networking","Ambiance house","Fin prévue autour de minuit"],note:"La première soirée est pensée pour briser les barrières et permettre aux premières connexions de naître naturellement."},
    {day:"Vendredi 28 août 2026",date:"L'immersion",items:["Conférences","Ateliers","Déjeuner","Sessions de networking","Temps libres au domaine","Piscine","Dîner","Soirée privée"],note:"Le programme détaillé et les horaires définitifs seront annoncés prochainement."},
    {day:"Samedi 29 août 2026",date:"Les dernières connexions",items:["Petit-déjeuner ou accueil","Dernières conférences","Tables rondes","Échanges libres","Déjeuner","Clôture","Départ des participants"],note:"Les horaires définitifs seront communiqués avant l'événement."},
  ],
  connections:["Relations durables","Collaborations","Partenaires","Conseils","Regards extérieurs","Nouvelles opportunités"],
  networkMoments:["Une idée qui devient plus claire","Une introduction qui ouvre une porte","Une conversation qui devient une collaboration","Un regard extérieur au bon moment"],
  tickets:[
    {name:"Pass Découverte",price:"Liste prioritaire ouverte",note:"Une journée",badge:"",featured:false,href:"#candidature",cta:"Candidater",benefits:["Accès à une journée définie","Conférences du jour","Networking","Accès au château","Repas précisés lors de la confirmation"]},
    {name:"Pass Expérience",price:"Liste prioritaire ouverte",note:"Événement complet",badge:"Expérience complète",featured:true,href:"#candidature",cta:"Candidater",benefits:["Accès du 27 au 29 août 2026","Toutes les conférences","Toutes les sessions de networking","Accès au château","Piscine","Repas prévus dans la formule","Soirées","Sans hébergement"]},
    {name:"Pass Immersion",price:"Liste prioritaire ouverte",note:"Événement complet + hébergement",badge:"Couchages limités",featured:false,href:"#candidature",cta:"Candidater",benefits:["Tous les avantages du Pass Expérience","Hébergement au château","Moments supplémentaires avec les participants","Accès à l'expérience complète sur place"]},
  ],
  scarcity:{title:"Un format volontairement limité.",text:"Destination Bretagne accueillera entre 30 et 50 participants. Ce format permet à chacun de réellement rencontrer les autres, d'échanger avec les intervenants et de ne pas disparaître dans une foule anonyme.",points:["Château entièrement privatisé","30 à 50 participants","Couchages encore plus limités","Proximité avec les intervenants","Expérience en petit comité"]},
  organizer:{name:"Aron",role:"Entrepreneur, organisateur et SaaS Founder",result:"10 k€ / mois",instagram:"@aron.etp",signature:"Aron — Organisateur de Destination Bretagne",text:["À force de développer des projets en ligne, j'ai compris que certaines évolutions ne venaient pas d'une nouvelle vidéo ou d'une nouvelle formation. Elles venaient d'une conversation, d'une rencontre ou d'une personne capable d'apporter le bon regard au bon moment.","Destination Bretagne est né de cette volonté : réunir dans un même lieu des personnes qui auraient tout intérêt à se connaître, mais qui ne se seraient peut-être jamais rencontrées autrement."]},
  faq:[
    ["Puis-je venir seul ?","Oui. Les premiers temps sont guidés pour faciliter naturellement les rencontres."],
    ["Puis-je participer si je débute ?","Oui. L'expérience accueille aussi bien des personnes qui lancent leur premier projet que des entrepreneurs confirmés."],
    ["Est-ce réservé aux fondateurs de SaaS ?","Non. Créateurs de contenu, freelances, dirigeants d'agence, infopreneurs et porteurs de projets ambitieux sont également concernés."],
    ["Où se trouve exactement le château ?","Le château se situe en Bretagne. L'adresse précise sera communiquée aux participants confirmés."],
    ["Quelles sont les dates officielles ?","Du jeudi 27 août 2026 au samedi 29 août 2026."],
    ["À quelle heure commence l'événement ?","L'accueil commence le jeudi 27 août 2026 à partir de 17 h 00."],
    ["Peut-on dormir sur place ?","Oui, avec le Pass Immersion et dans la limite des couchages disponibles."],
    ["Les repas sont-ils inclus ?","Ils dépendent de la formule choisie. Le détail sera précisé avant la réservation."],
    ["Comment se déroule le networking ?","Les rencontres alternent temps guidés, repas, activités et échanges libres dans le domaine."],
    ["Quel est le nombre de participants ?","Entre 30 et 50 entrepreneurs."],
    ["Quelles sont les différences entre les pass ?","La durée d'accès, les repas et l'hébergement distinguent les trois formules."],
    ["Les billets sont-ils remboursables ?","Les conditions seront précisées dans les CGV avant l'ouverture des ventes."],
    ["Quand le programme définitif sera-t-il publié ?","Cette information sera communiquée prochainement aux participants."],
    ["Les intervenants sont-ils tous confirmés ?","Trois intervenants sont confirmés. Les trois prochains profils seront annoncés après confirmation."],
    ["Comment recevoir les informations pratiques ?","Les informations seront envoyées par email aux participants confirmés."],
  ] as [string,string][],
  final:{eyebrow:"27 — 29 AOÛT 2026 · BRETAGNE",title:"Les opportunités appartiennent à ceux qui passent à l'action.",text:"Dans quelques mois, tu ne te souviendras peut-être pas de chaque conférence. Mais tu pourrais encore parler aux personnes rencontrées ici.",primaryCta:"Candidater",secondaryCta:"Poser une question",facts:["Château privatisé","30 à 50 participants","Du 27 au 29 août 2026"]},
  profiles:["Entrepreneurs débutants","Entrepreneurs confirmés","Créateurs de contenu","Fondateurs de SaaS","Freelances","Dirigeants d'agence","Infopreneurs","Porteurs de projets ambitieux"],
} as const;

export const event = eventConfig;
export type EventConfig = typeof eventConfig;
